version: "3.9"

services:
  db:
    image: postgres:16
    container_name: tslgpt_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tslgpt
    ports:
      - "5434:5432"
    volumes:
      - /opt/tslgpt/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: tslgpt_backend
    restart: unless-stopped
    environment:
      PORT: 3300            # ВАЖНО: порт внутри контейнера
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/tslgpt?schema=public
      JWT_SECRET: supersecret_dev_key_change_me
      CORS_ORIGIN: http://localhost:3007
    ports:
      - "3307:3300"         # хост:контейнер
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma generate && (npx prisma migrate deploy || npx prisma db push) && npm run dev"

  frontend:
    build: ./frontend
    container_name: tslgpt_frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3307
    ports:
      - "3007:3000"
    depends_on:
      - backend
